name: Lint HTML Files

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Super Linter (HTML Only)
        uses: super-linter/super-linter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # ✅ Fix authentication issue
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_HTML: true
          DEFAULT_BRANCH: main 
